// Code generated by blocks. DO NOT EDIT.
package html

import "github.com/mbertschler/blocks/html/attr"

func A(attr attr.Attributes, children ...Block) Block {
	return newElement("a", attr, children, 0)
}
func Abbr(attr attr.Attributes, children ...Block) Block {
	return newElement("abbr", attr, children, 0)
}
func Address(attr attr.Attributes, children ...Block) Block {
	return newElement("address", attr, children, 0)
}
func Area(attr attr.Attributes, children ...Block) Block {
	return newElement("area", attr, children, 0)
}
func Article(attr attr.Attributes, children ...Block) Block {
	return newElement("article", attr, children, 0)
}
func Aside(attr attr.Attributes, children ...Block) Block {
	return newElement("aside", attr, children, 0)
}
func Audio(attr attr.Attributes, children ...Block) Block {
	return newElement("audio", attr, children, 0)
}
func B(attr attr.Attributes, children ...Block) Block {
	return newElement("b", attr, children, 0)
}
func Base(attr attr.Attributes, children ...Block) Block {
	return newElement("base", attr, children, 0)
}
func Bdi(attr attr.Attributes, children ...Block) Block {
	return newElement("bdi", attr, children, 0)
}
func Bdo(attr attr.Attributes, children ...Block) Block {
	return newElement("bdo", attr, children, 0)
}
func Blockquote(attr attr.Attributes, children ...Block) Block {
	return newElement("blockquote", attr, children, 0)
}
func Body(attr attr.Attributes, children ...Block) Block {
	return newElement("body", attr, children, 0)
}
func Br(attr attr.Attributes) Block {
	return newElement("br", attr, nil, Void)
}
func Button(attr attr.Attributes, children ...Block) Block {
	return newElement("button", attr, children, 0)
}
func Canvas(attr attr.Attributes, children ...Block) Block {
	return newElement("canvas", attr, children, 0)
}
func Caption(attr attr.Attributes, children ...Block) Block {
	return newElement("caption", attr, children, 0)
}
func Cite(attr attr.Attributes, children ...Block) Block {
	return newElement("cite", attr, children, 0)
}
func Code(attr attr.Attributes, children ...Block) Block {
	return newElement("code", attr, children, 0)
}
func Col(attr attr.Attributes, children ...Block) Block {
	return newElement("col", attr, children, 0)
}
func Colgroup(attr attr.Attributes, children ...Block) Block {
	return newElement("colgroup", attr, children, 0)
}
func Data(attr attr.Attributes, children ...Block) Block {
	return newElement("data", attr, children, 0)
}
func Datalist(attr attr.Attributes, children ...Block) Block {
	return newElement("datalist", attr, children, 0)
}
func Dd(attr attr.Attributes, children ...Block) Block {
	return newElement("dd", attr, children, 0)
}
func Del(attr attr.Attributes, children ...Block) Block {
	return newElement("del", attr, children, 0)
}
func Details(attr attr.Attributes, children ...Block) Block {
	return newElement("details", attr, children, 0)
}
func Dfn(attr attr.Attributes, children ...Block) Block {
	return newElement("dfn", attr, children, 0)
}
func Dialog(attr attr.Attributes, children ...Block) Block {
	return newElement("dialog", attr, children, 0)
}
func Div(attr attr.Attributes, children ...Block) Block {
	return newElement("div", attr, children, 0)
}
func Dl(attr attr.Attributes, children ...Block) Block {
	return newElement("dl", attr, children, 0)
}
func Dt(attr attr.Attributes, children ...Block) Block {
	return newElement("dt", attr, children, 0)
}
func Em(attr attr.Attributes, children ...Block) Block {
	return newElement("em", attr, children, 0)
}
func Embed(attr attr.Attributes, children ...Block) Block {
	return newElement("embed", attr, children, 0)
}
func Fieldset(attr attr.Attributes, children ...Block) Block {
	return newElement("fieldset", attr, children, 0)
}
func Figcaption(attr attr.Attributes, children ...Block) Block {
	return newElement("figcaption", attr, children, 0)
}
func Figure(attr attr.Attributes, children ...Block) Block {
	return newElement("figure", attr, children, 0)
}
func Footer(attr attr.Attributes, children ...Block) Block {
	return newElement("footer", attr, children, 0)
}
func Form(attr attr.Attributes, children ...Block) Block {
	return newElement("form", attr, children, 0)
}
func H1(attr attr.Attributes, children ...Block) Block {
	return newElement("h1", attr, children, 0)
}
func H2(attr attr.Attributes, children ...Block) Block {
	return newElement("h2", attr, children, 0)
}
func H3(attr attr.Attributes, children ...Block) Block {
	return newElement("h3", attr, children, 0)
}
func H4(attr attr.Attributes, children ...Block) Block {
	return newElement("h4", attr, children, 0)
}
func H5(attr attr.Attributes, children ...Block) Block {
	return newElement("h5", attr, children, 0)
}
func H6(attr attr.Attributes, children ...Block) Block {
	return newElement("h6", attr, children, 0)
}
func Head(attr attr.Attributes, children ...Block) Block {
	return newElement("head", attr, children, 0)
}
func Header(attr attr.Attributes, children ...Block) Block {
	return newElement("header", attr, children, 0)
}
func Hgroup(attr attr.Attributes, children ...Block) Block {
	return newElement("hgroup", attr, children, 0)
}
func Hr(attr attr.Attributes) Block {
	return newElement("hr", attr, nil, Void)
}
func Html(attr attr.Attributes, children ...Block) Block {
	return newElement("html", attr, children, 0)
}
func I(attr attr.Attributes, children ...Block) Block {
	return newElement("i", attr, children, 0)
}
func Iframe(attr attr.Attributes, children ...Block) Block {
	return newElement("iframe", attr, children, 0)
}
func Img(attr attr.Attributes) Block {
	return newElement("img", attr, nil, Void)
}
func Input(attr attr.Attributes) Block {
	return newElement("input", attr, nil, Void)
}
func Ins(attr attr.Attributes, children ...Block) Block {
	return newElement("ins", attr, children, 0)
}
func Kbd(attr attr.Attributes, children ...Block) Block {
	return newElement("kbd", attr, children, 0)
}
func Label(attr attr.Attributes, children ...Block) Block {
	return newElement("label", attr, children, 0)
}
func Legend(attr attr.Attributes, children ...Block) Block {
	return newElement("legend", attr, children, 0)
}
func Li(attr attr.Attributes, children ...Block) Block {
	return newElement("li", attr, children, 0)
}
func Link(attr attr.Attributes) Block {
	return newElement("link", attr, nil, Void)
}
func Main(attr attr.Attributes, children ...Block) Block {
	return newElement("main", attr, children, 0)
}
func Map(attr attr.Attributes, children ...Block) Block {
	return newElement("map", attr, children, 0)
}
func Mark(attr attr.Attributes, children ...Block) Block {
	return newElement("mark", attr, children, 0)
}
func Menu(attr attr.Attributes, children ...Block) Block {
	return newElement("menu", attr, children, 0)
}
func Meta(attr attr.Attributes) Block {
	return newElement("meta", attr, nil, Void)
}
func Meter(attr attr.Attributes, children ...Block) Block {
	return newElement("meter", attr, children, 0)
}
func Nav(attr attr.Attributes, children ...Block) Block {
	return newElement("nav", attr, children, 0)
}
func Noscript(attr attr.Attributes, children ...Block) Block {
	return newElement("noscript", attr, children, 0)
}
func Object(attr attr.Attributes, children ...Block) Block {
	return newElement("object", attr, children, 0)
}
func Ol(attr attr.Attributes, children ...Block) Block {
	return newElement("ol", attr, children, 0)
}
func Optgroup(attr attr.Attributes, children ...Block) Block {
	return newElement("optgroup", attr, children, 0)
}
func Option(attr attr.Attributes, children ...Block) Block {
	return newElement("option", attr, children, 0)
}
func Output(attr attr.Attributes, children ...Block) Block {
	return newElement("output", attr, children, 0)
}
func P(attr attr.Attributes, children ...Block) Block {
	return newElement("p", attr, children, 0)
}
func Picture(attr attr.Attributes, children ...Block) Block {
	return newElement("picture", attr, children, 0)
}
func Portal(attr attr.Attributes, children ...Block) Block {
	return newElement("portal", attr, children, 0)
}
func Pre(attr attr.Attributes, children ...Block) Block {
	return newElement("pre", attr, children, NoWhitespace)
}
func Progress(attr attr.Attributes, children ...Block) Block {
	return newElement("progress", attr, children, 0)
}
func Q(attr attr.Attributes, children ...Block) Block {
	return newElement("q", attr, children, 0)
}
func Rp(attr attr.Attributes, children ...Block) Block {
	return newElement("rp", attr, children, 0)
}
func Rt(attr attr.Attributes, children ...Block) Block {
	return newElement("rt", attr, children, 0)
}
func Ruby(attr attr.Attributes, children ...Block) Block {
	return newElement("ruby", attr, children, 0)
}
func S(attr attr.Attributes, children ...Block) Block {
	return newElement("s", attr, children, 0)
}
func Samp(attr attr.Attributes, children ...Block) Block {
	return newElement("samp", attr, children, 0)
}
func Script(attr attr.Attributes, children ...Block) Block {
	return newElement("script", attr, children, JSElement)
}
func Section(attr attr.Attributes, children ...Block) Block {
	return newElement("section", attr, children, 0)
}
func Select(attr attr.Attributes, children ...Block) Block {
	return newElement("select", attr, children, 0)
}
func Slot(attr attr.Attributes, children ...Block) Block {
	return newElement("slot", attr, children, 0)
}
func Small(attr attr.Attributes, children ...Block) Block {
	return newElement("small", attr, children, 0)
}
func Source(attr attr.Attributes, children ...Block) Block {
	return newElement("source", attr, children, 0)
}
func Span(attr attr.Attributes, children ...Block) Block {
	return newElement("span", attr, children, 0)
}
func Strong(attr attr.Attributes, children ...Block) Block {
	return newElement("strong", attr, children, 0)
}
func Style(attr attr.Attributes, children ...Block) Block {
	return newElement("style", attr, children, CSSElement)
}
func Sub(attr attr.Attributes, children ...Block) Block {
	return newElement("sub", attr, children, 0)
}
func Summary(attr attr.Attributes, children ...Block) Block {
	return newElement("summary", attr, children, 0)
}
func Sup(attr attr.Attributes, children ...Block) Block {
	return newElement("sup", attr, children, 0)
}
func Table(attr attr.Attributes, children ...Block) Block {
	return newElement("table", attr, children, 0)
}
func Tbody(attr attr.Attributes, children ...Block) Block {
	return newElement("tbody", attr, children, 0)
}
func Td(attr attr.Attributes, children ...Block) Block {
	return newElement("td", attr, children, 0)
}
func Template(attr attr.Attributes, children ...Block) Block {
	return newElement("template", attr, children, 0)
}
func Textarea(attr attr.Attributes, children ...Block) Block {
	return newElement("textarea", attr, children, NoWhitespace)
}
func Tfoot(attr attr.Attributes, children ...Block) Block {
	return newElement("tfoot", attr, children, 0)
}
func Th(attr attr.Attributes, children ...Block) Block {
	return newElement("th", attr, children, 0)
}
func Thead(attr attr.Attributes, children ...Block) Block {
	return newElement("thead", attr, children, 0)
}
func Time(attr attr.Attributes, children ...Block) Block {
	return newElement("time", attr, children, 0)
}
func Title(attr attr.Attributes, children ...Block) Block {
	return newElement("title", attr, children, 0)
}
func Tr(attr attr.Attributes, children ...Block) Block {
	return newElement("tr", attr, children, 0)
}
func Track(attr attr.Attributes, children ...Block) Block {
	return newElement("track", attr, children, 0)
}
func U(attr attr.Attributes, children ...Block) Block {
	return newElement("u", attr, children, 0)
}
func Ul(attr attr.Attributes, children ...Block) Block {
	return newElement("ul", attr, children, 0)
}
func Var(attr attr.Attributes, children ...Block) Block {
	return newElement("var", attr, children, 0)
}
func Video(attr attr.Attributes, children ...Block) Block {
	return newElement("video", attr, children, 0)
}
func Wbr(attr attr.Attributes, children ...Block) Block {
	return newElement("wbr", attr, children, 0)
}
